services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        depends_on:
            - db
        ports:
            - "8001:8000"
        environment:
            - DB_CONNECTION=mysql
            - DB_HOST=db
            - DB_PORT=3306
            - DB_DATABASE=admin
            - DB_USERNAME=admin
            - DB_PASSWORD=admin

    db:
        image: mysql:8.0
        environment:
            MYSQL_ROOT_PASSWORD: admin
            MYSQL_DATABASE: admin
            MYSQL_USER: admin
            MYSQL_PASSWORD: admin
        ports:
            - "3305:3306"
        volumes:
            - db_data:/var/lib/mysql

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        depends_on:
            - db
        environment:
            PMA_HOST: db
            MYSQL_ROOT_PASSWORD: admin
        ports:
            - "8081:80"
        restart: always

volumes:
    db_data:
